// Тексты превью страниц сайта на трёх языках: и для картинок (scripts/build-og-pages.js → assets/og/<имя>[-ro|-en].png),
// и для мета-тегов при ?lang=ro|en (api/page-meta.js). k — метка раздела, h — заголовок на картинке, s — подпись, t — <title>/og:title, d — описание.
// RU-версия дублирует то, что уже стоит в HTML страниц (для картинок); отдельные ro-* страницы описаны в scripts/build-og-pages.js.
const PAGES = {
  index:{path:"", img:"hero-bg-v43.jpg",
    ru:{k:"ПОД КЛЮЧ ИЗ США И КАНАДЫ", h:"Авто из США и Канады под ключ в Молдову", s:"Расчёт полной стоимости онлайн: Copart, IAAI, Manheim"},
    ro:{k:"LA CHEIE DIN SUA ȘI CANADA", h:"Mașini din SUA și Canada la cheie în Moldova", s:"Calcul complet online: Copart, IAAI, Manheim", t:"Apex Auto — mașini din SUA și Canada la cheie în Moldova", d:"Calculează costul complet al unei mașini din SUA și Canada până la Chișinău: licitații Copart, IAAI, Manheim, livrare și vămuire."},
    en:{k:"TURNKEY DELIVERY", h:"Cars from the USA and Canada to Moldova", s:"Full cost online: Copart, IAAI, Manheim", t:"Apex Auto — cars from the USA and Canada turnkey to Moldova", d:"Get the full turnkey cost of a car from the USA and Canada to Chisinau: Copart, IAAI and Manheim auctions, shipping and customs."}},
  auctions:{path:"auctions", img:"hot/honda-accord.jpg",
    ru:{k:"КАТАЛОГ АУКЦИОНОВ", h:"Аукционы Copart и IAAI", s:"Поиск по VIN и лоту · фото · расчёт под ключ до Кишинёва"},
    ro:{k:"CATALOG LICITAȚII", h:"Licitații Copart și IAAI", s:"Căutare după VIN și lot · foto · calcul la cheie până la Chișinău", t:"Licitații Copart și IAAI — catalog auto din SUA și Canada | Apex Auto", d:"Catalog de mașini de la licitațiile Copart și IAAI: căutare după VIN și lot, filtre, fotografii și calcul la cheie până la Chișinău."},
    en:{k:"AUCTION CATALOG", h:"Copart and IAAI auctions", s:"Search by VIN and lot · photos · turnkey estimate to Chisinau", t:"Copart and IAAI auctions — cars from the USA and Canada | Apex Auto", d:"Catalog of cars from Copart and IAAI auctions: search by VIN and lot, filters, photos and a turnkey estimate to Chisinau."}},
  hot:{path:"in-transit", page:"in-transit", img:"hot/mercedes-e300.jpg",
    ru:{k:"АВТО В ПУТИ", h:"Продажа авто в пути", s:"Уже куплены и едут в Молдову — можно забронировать"},
    ro:{k:"AUTO ÎN TRANZIT", h:"Mașini în tranzit", s:"Deja cumpărate și în drum spre Moldova — se pot rezerva", t:"Mașini în tranzit — din SUA în Moldova | Apex Auto", d:"Mașini din SUA și Canada deja cumpărate și în drum spre Moldova: preț, foto, descriere și urmărire după VIN."},
    en:{k:"CARS IN TRANSIT", h:"Cars in transit", s:"Already bought and on the way to Moldova — reserve yours", t:"Cars in transit — from the USA to Moldova | Apex Auto", d:"Cars from the USA and Canada already purchased and on their way to Moldova: price, photos, description and VIN tracking."}},
  about:{path:"about", img:"hot/founder-auction.jpg",
    ru:{k:"ОСНОВАТЕЛЬ", h:"Федор Чебан", s:"В авто-бизнесе с 2016 года · Copart · IAAI · Manheim"},
    ro:{k:"FONDATOR", h:"Fedor Ceban", s:"În business-ul auto din 2016 · Copart · IAAI · Manheim", t:"Povestea mea — Fedor Ceban, fondatorul Apex Auto", d:"Fedor Ceban, fondatorul Apex Auto: experiență din 2016, licitații Copart, IAAI, Manheim, verificarea mașinii înainte de cumpărare."},
    en:{k:"FOUNDER", h:"Fedor Ceban", s:"In the car business since 2016 · Copart · IAAI · Manheim", t:"My story — Fedor Ceban, founder of Apex Auto", d:"Fedor Ceban, founder of Apex Auto: experience since 2016, Copart, IAAI and Manheim auctions, checking every car before you buy."}},
  contacts:{path:"contacts", img:"hot/founder-auction.jpg",
    ru:{k:"КОНТАКТЫ", h:"Связаться с Apex Auto", s:"Telegram @fedukusa · WhatsApp · 068-832-032"},
    ro:{k:"CONTACTE", h:"Contactați Apex Auto", s:"Telegram @fedukusa · WhatsApp · 068-832-032", t:"Contacte — Apex Auto | Telegram, WhatsApp, telefon", d:"Contactați Apex Auto: Telegram @fedukusa, canal @fedukauto, WhatsApp și telefon 068-832-032. Calcul, selecție și livrare."},
    en:{k:"CONTACTS", h:"Contact Apex Auto", s:"Telegram @fedukusa · WhatsApp · 068-832-032", t:"Contacts — Apex Auto | Telegram, WhatsApp, phone", d:"Contact Apex Auto: Telegram @fedukusa, channel @fedukauto, WhatsApp and phone 068-832-032. Estimates, car search and delivery."}},
  guide:{path:"guide", img:"hot/delivery-sea.jpg",
    ru:{k:"РУКОВОДСТВО 2026", h:"Как привезти авто из США и Канады в Молдову", s:"Аукцион, доставка, таможня — пошагово"},
    ro:{k:"GHID 2026", h:"Cum aduci o mașină din SUA și Canada în Moldova", s:"Licitație, livrare, vămuire — pas cu pas", t:"Cum aduci o mașină din SUA și Canada în Moldova în 2026 — ghid complet", d:"Ghid pas cu pas pentru livrarea unei mașini din SUA și Canada în Moldova: licitații Copart și IAAI, costuri, termene, vămuire."},
    en:{k:"GUIDE 2026", h:"How to bring a car from the USA and Canada to Moldova", s:"Auction, shipping, customs — step by step", t:"How to bring a car from the USA and Canada to Moldova in 2026 — full guide", d:"Step-by-step guide to shipping a car from the USA and Canada to Moldova: Copart and IAAI auctions, costs, timelines, customs."}},
  customs:{path:"customs",
    ru:{k:"РАСТАМОЖКА 2026", h:"Растаможка авто в Молдове", s:"Акцизы, таблицы, льготы для EV и гибридов"},
    ro:{k:"VĂMUIRE 2026", h:"Vămuirea auto în Moldova", s:"Accize, tabele, scutiri pentru EV și hibride", t:"Vămuirea auto în Moldova 2026 — accize, tabele, scutiri", d:"Tabele de accize 2026 pentru mașini, moto și camioane în Moldova: tarife după motor și vârstă, scutiri pentru EV și hibride."},
    en:{k:"CUSTOMS 2026", h:"Car customs clearance in Moldova", s:"Excise tables and benefits for EVs and hybrids", t:"Car customs clearance in Moldova 2026 — excise, tables, benefits", d:"2026 excise tables for cars, motorcycles and trucks in Moldova: rates by engine and age, benefits for EVs and hybrids."}},
  tracking:{path:"tracking", img:"hot/delivery-sea.jpg",
    ru:{k:"ОТСЛЕЖИВАНИЕ", h:"Где ваш автомобиль", s:"Введите VIN или номер лота — покажем этапы доставки"},
    ro:{k:"URMĂRIRE", h:"Unde este mașina dvs.", s:"Introduceți VIN sau numărul lotului — vedeți etapele livrării", t:"Urmărire auto din SUA și Canada — verificați livrarea | Apex Auto", d:"Introduceți VIN sau numărul lotului — vă arătăm etapele livrării mașinii din SUA sau Canada în Moldova."},
    en:{k:"TRACKING", h:"Where is your car", s:"Enter the VIN or lot number — see the delivery stages", t:"Car tracking from the USA and Canada — check your delivery | Apex Auto", d:"Enter your VIN or lot number and see every stage of delivery from the USA or Canada to Moldova."}},
  "auction-fees":{path:"auction-fees",
    ru:{k:"СБОРЫ АУКЦИОНОВ", h:"Auction Fee на Copart и IAAI", s:"Из чего состоят сборы и как их посчитать"},
    ro:{k:"TAXELE LICITAȚIILOR", h:"Auction Fee pe Copart și IAAI", s:"Din ce constau taxele și cum le calculezi", t:"Auction Fee pe Copart și IAAI: din ce constau taxele licitației", d:"Tabel cu taxele Copart, IAAI și Manheim după prețul lotului, exemplu de calcul și comisionul deschis al Apex Auto."},
    en:{k:"AUCTION FEES", h:"Auction fees on Copart and IAAI", s:"What they consist of and how to calculate them", t:"Copart and IAAI auction fees: what they consist of", d:"Copart, IAAI and Manheim fee tables by lot price, a real calculation example and Apex Auto's open commission."}},
  blog:{path:"blog",
    ru:{k:"БЛОГ", h:"Блог об авто из США и Канады", s:"Гайды и разборы: реальные цифры и опыт"},
    ro:{k:"BLOG", h:"Blog despre mașini din SUA și Canada", s:"Ghiduri și analize: cifre reale și experiență", t:"Blog despre mașini din SUA și Canada — ghiduri și analize | Apex Auto", d:"Cum cumperi la Copart și IAAI, vămuirea în Moldova, taxele licitațiilor, verificarea VIN. Cifre reale și experiență."},
    en:{k:"BLOG", h:"Blog about cars from the USA and Canada", s:"Guides and analysis: real numbers and experience", t:"Blog about cars from the USA and Canada — guides and analysis | Apex Auto", d:"How to buy on Copart and IAAI, customs in Moldova, auction fees and VIN checks. Real numbers and hands-on experience."}},
  damages:{path:"damages",
    ru:{k:"ПОВРЕЖДЕНИЯ", h:"Какие повреждения опасны, а какие нет", s:"Как читать Primary Damage и выбирать выгодные лоты"},
    ro:{k:"DAUNE", h:"Ce daune sunt periculoase și care nu", s:"Cum citești Primary Damage și alegi loturi avantajoase", t:"Ce daune auto de la licitație sunt periculoase și care nu", d:"Ce loturi sunt cu adevărat avantajoase, de ce grindina e o capcană și cum citești Primary Damage."},
    en:{k:"DAMAGE", h:"Which damage is dangerous and which is not", s:"How to read Primary Damage and pick good lots", t:"Which auction car damage is dangerous and which is not", d:"Which lots are really worth it, why hail is a trap and how to read Primary Damage."}},
  shipping:{path:"shipping", img:"hot/delivery-sea.jpg",
    ru:{k:"ДОСТАВКА", h:"Доставка авто из США и Канады", s:"Маршруты, порты и сроки до Кишинёва"},
    ro:{k:"LIVRARE", h:"Livrarea auto din SUA și Canada", s:"Rute, porturi și termene până la Chișinău", t:"Livrarea auto din SUA și Canada în Moldova: rute, porturi, termene", d:"Klaipeda, Constanța, Bremerhaven sau Rotterdam? Compararea rutelor de livrare din America de Nord până la Chișinău."},
    en:{k:"SHIPPING", h:"Car shipping from the USA and Canada", s:"Routes, ports and timelines to Chisinau", t:"Car shipping from the USA and Canada to Moldova: routes, ports, timelines", d:"Klaipeda, Constanta, Bremerhaven or Rotterdam? A comparison of shipping routes from North America to Chisinau."}},
  "ship-my-car":{path:"ship-my-car", img:"hot/delivery-sea.jpg",
    ru:{k:"ЛИЧНОЕ АВТО", h:"Отправить свою машину домой в Молдову", s:"Заберём от дома в США и доставим до Кишинёва"},
    ro:{k:"MAȘINA PERSONALĂ", h:"Trimite-ți mașina acasă în Moldova", s:"O ridicăm de la domiciliul din SUA și o livrăm la Chișinău", t:"Trimite-ți mașina din SUA acasă în Moldova | Apex Auto", d:"Ridicăm mașina personală de la domiciliul din SUA sau o primim la depozit și o livrăm până la Chișinău. Pentru moldovenii care muncesc în SUA."},
    en:{k:"YOUR OWN CAR", h:"Ship your car home to Moldova", s:"We pick it up in the USA and deliver it to Chisinau", t:"Ship your own car from the USA home to Moldova | Apex Auto", d:"We pick up your personal car from your US home or receive it at our yard and deliver it to Chisinau. For Moldovans working in the USA."}},
  "tesla-model-3":{path:"tesla-model-3",
    ru:{k:"ПРИМЕР РАСЧЁТА", h:"Tesla Model 3 из США в Молдову", s:"Цена под ключ до Кишинёва"},
    ro:{k:"EXEMPLU DE CALCUL", h:"Tesla Model 3 din SUA în Moldova", s:"Prețul la cheie până la Chișinău", t:"Tesla Model 3 din SUA în Moldova: calculul prețului la cheie", d:"Cât costă să aduci o Tesla Model 3 din SUA în Moldova: prețuri la licitațiile Copart și IAAI și un exemplu de calcul la cheie."},
    en:{k:"COST EXAMPLE", h:"Tesla Model 3 from the USA to Moldova", s:"Turnkey price to Chisinau", t:"Tesla Model 3 from the USA to Moldova: turnkey price calculation", d:"What it costs to bring a Tesla Model 3 from the USA to Moldova: Copart and IAAI prices and a turnkey calculation example."}},
  "toyota-rav4":{path:"toyota-rav4",
    ru:{k:"ПРИМЕР РАСЧЁТА", h:"Toyota RAV4 из США в Молдову", s:"Сколько стоит под ключ и льгота на гибрид"},
    ro:{k:"EXEMPLU DE CALCUL", h:"Toyota RAV4 din SUA în Moldova", s:"Cât costă la cheie și scutirea pentru hibrid", t:"Toyota RAV4 din SUA în Moldova: cât costă la cheie", d:"Prețuri reale de licitație pe ani, exemplu de calcul până la Chișinău și reducerea de −25% la vămuire pentru hibrid."},
    en:{k:"COST EXAMPLE", h:"Toyota RAV4 from the USA to Moldova", s:"Turnkey cost and the hybrid customs discount", t:"Toyota RAV4 from the USA to Moldova: how much it costs turnkey", d:"Real auction prices by year, a calculation to Chisinau and the −25% customs discount for hybrids."}},
  "usa-vs-europe":{path:"usa-vs-europe",
    ru:{k:"СРАВНЕНИЕ", h:"Авто из США или из Европы", s:"Что выгоднее для Молдовы: цены, пробег, растаможка"},
    ro:{k:"COMPARAȚIE", h:"Mașină din SUA sau din Europa", s:"Ce e mai avantajos pentru Moldova: preț, rulaj, vămuire", t:"Mașină din SUA sau din Europa: ce e mai avantajos pentru Moldova", d:"Prețuri, kilometraj mărit, Carfax, vămuire — o comparație sinceră a celor două căi și cazurile în care Europa chiar câștigă."},
    en:{k:"COMPARISON", h:"A car from the USA or from Europe", s:"What is better for Moldova: price, mileage, customs", t:"A car from the USA or from Europe: what is better for Moldova", d:"Prices, rolled-back mileage, Carfax, customs — an honest comparison of the two routes and the cases where Europe really wins."}},
  "vin-check":{path:"vin-check",
    ru:{k:"ПРОВЕРКА VIN", h:"Как проверить VIN перед покупкой", s:"Carfax, AutoCheck и красные флаги в истории"},
    ro:{k:"VERIFICARE VIN", h:"Cum verifici VIN-ul înainte de cumpărare", s:"Carfax, AutoCheck și semnale de alarmă în istoric", t:"Cum verifici VIN-ul unei mașini înainte de cumpărarea la licitații din SUA și Canada", d:"Carfax, AutoCheck, servicii gratuite și semnale de alarmă în istoricul mașinii. Verificare VIN gratuită de la Apex Auto."},
    en:{k:"VIN CHECK", h:"How to check a VIN before you buy", s:"Carfax, AutoCheck and red flags in the history", t:"How to check a car's VIN before buying at US and Canadian auctions", d:"Carfax, AutoCheck, free services and red flags in a car's history. Free VIN check from Apex Auto."}},
  cases:{path:"cases",
    ru:{k:"КЕЙСЫ", h:"Реальные машины под ключ", s:"Лот, все расходы и итог для клиента"},
    ro:{k:"CAZURI", h:"Mașini reale la cheie", s:"Lot, toate costurile și totalul pentru client", t:"Cazuri: mașini reale la cheie — Apex Auto", d:"Tranzacții reale Apex Auto: lotul, toate costurile, totalul la cheie și foto la predare."},
    en:{k:"CASES", h:"Real cars, delivered turnkey", s:"The lot, every cost and the final price", t:"Cases: real cars delivered turnkey — Apex Auto", d:"Real Apex Auto deals: the lot, all costs, the turnkey total and delivery photos."}},
  privacy:{path:"privacy",
    ru:{k:"ДОКУМЕНТЫ", h:"Политика конфиденциальности", s:"Как Apex Auto обрабатывает данные"},
    ro:{k:"DOCUMENTE", h:"Politica de confidențialitate", s:"Cum prelucrează Apex Auto datele", t:"Politica de confidențialitate — Apex Auto", d:"Cum prelucrează Apex Auto datele personale și care sunt drepturile utilizatorilor."},
    en:{k:"DOCUMENTS", h:"Privacy policy", s:"How Apex Auto handles your data", t:"Privacy policy — Apex Auto", d:"How Apex Auto processes personal data and what rights users have."}}
};
module.exports = {PAGES};
