-- Закрытая экспертная таблица оценки (ориентир ставки). RLS включён и политик НЕТ:
-- читать/писать может только сервер сервисным ключом. Публичным ключом таблица не видна.
create table if not exists public.price_guide (
  id          bigint generated by default as identity primary key,
  name        text not null,            -- как в таблице Федора: «bmw g30 530e LCI 21-23»
  note        text,                     -- заметка (версия/надбавки) — только для админки
  make        text not null,
  tokens      text[] not null default '{}',   -- что должно найтись в модели/названии/коде кузова
  year_from   int,
  year_to     int,
  fuel        text not null default 'any',    -- any | gas | hybrid | plugin | electric | diesel
  base_price  numeric not null,         -- «актуаластат»: средняя цена продаж кузова
  k           numeric not null default 1.2,
  active      boolean not null default true,
  updated_at  timestamptz not null default now()
);
alter table public.price_guide enable row level security;
-- Заодно закрываем от публичного ключа CRM-таблицы (сервер ходит сервисным ключом — ему RLS не мешает).
alter table public.customers    enable row level security;
alter table public.leads        enable row level security;
alter table public.vehicles     enable row level security;
alter table public.site_content enable row level security;
notify pgrst, 'reload schema';
