-- Уведомления в Telegram: новые лоты по сохранённому поиску + напоминания о торгах лота.
-- Выполнять в Supabase SQL Editor (каждый блок отдельным запуском, если редактор ругается на транзакцию).

create table if not exists public.alert_links (
  token      text primary key,               -- секрет клиента (хранится в его браузере)
  chat_id    bigint,                         -- Telegram chat, пока null — Start ещё не нажат
  lang       text not null default 'ru',
  ip_hash    text,
  created_at timestamptz not null default now(),
  bound_at   timestamptz
);
create index if not exists idx_alert_links_chat on public.alert_links (chat_id);
create index if not exists idx_alert_links_ip   on public.alert_links (ip_hash, created_at);

create table if not exists public.alert_subs (
  id         bigint generated by default as identity primary key,
  token      text not null references public.alert_links(token) on delete cascade,
  kind       text not null check (kind in ('search','lot')),
  name       text,
  qs         text,                           -- kind=search: строка фильтров каталога
  lot_id     text,                           -- kind=lot: copart-123 / iaai-456
  lot_title  text,
  sale_date  timestamptz,
  stage      int not null default 0,         -- lot: 1 = «через час» отправлено, 2 = «играет», 3 = итог
  active     boolean not null default true,
  last_check timestamptz not null default now(),
  last_sent  timestamptz,
  sent_count int not null default 0,
  created_at timestamptz not null default now()
);
create index if not exists idx_alert_subs_token  on public.alert_subs (token);
create index if not exists idx_alert_subs_active on public.alert_subs (kind, active, last_check);

create table if not exists public.alert_meta (
  k          text primary key,
  v          jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.alert_links enable row level security;
alter table public.alert_subs  enable row level security;
alter table public.alert_meta  enable row level security;

-- «Новые лоты»: когда лот впервые попал в нашу базу (синк при обновлении это поле не трогает).
-- ADD COLUMN с DEFAULT now() в Postgres 11+ мгновенный, таблицу не переписывает.
alter table public.api_lots add column if not exists first_seen timestamptz default now();

notify pgrst, 'reload schema';
